### ISSUE TITLE
Add some screenshots/demo

### ISSUE THREAD

**Issue by MadLittleMods** [jacobschultz/scout-public#15]
Add some screenshots/demo of the webapp 🤞 

I don't want to set up the project just to see how it looks

**Comment by jacobschultz** [comment]
Hey @MadLittleMods! 

I'll get those added for you in the next few days, thanks for the suggestion.

**Comment by jacobschultz** [comment]
Here is an album of screenshots: https://imgur.com/a/qEfd0KM

The readme has also been updated with these.

**Comment by MadLittleMods** [comment]
@jacobschultz Thanks, would be good to inline a few (easy to miss the link in the readme)
